on:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: depot-ubuntu-latest
    steps:
      #      - name: Checkout repository
      #        uses: actions/checkout@v6
      #        with:
      #          fetch-depth: 1

      - name: Checkout repository (sparse)
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            package.json
            pnpm-lock.yaml
            pnpm-workspace.yaml
          sparse-checkout-cone-mode: false

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ./package.json

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure pnpm store
        run: pnpm config set store-dir /opt/pnpm-store --global

      - name: Prime dependency store
        run: pnpm install --frozen-lockfile

      - name: Remove git state before snapshot
        run: rm -rf .git

      - name: Snapshot CI image
        uses: depot/snapshot-action@v1
        with:
          image: d58mfwccbf.registry.depot.dev/nano-base:latest
