on:
  workflow_dispatch:

jobs:
  test:
    runs-on:
      size: 2x8
      image: d58mfwccbf.registry.depot.dev/nano-base:latest
    steps:
      - uses: actions/checkout@v4

      - name: List all files
        run: ls -la

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ./package.json
      - name: Verify node and pnpm are available
        run: |
          node --version
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
